import { Component, DestroyRef, inject, OnInit, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import { finalize, Subject, switchMap, tap, catchError, EMPTY } from 'rxjs';
import { PedidosApiService } from '../core/api';
import { SessionService } from '../core/session';
import { OrderDetail, ProcessStep } from '../core/models';
import { errorMessage, Notifications } from '../core/errors';
import { activeOrder, pollOrder } from '../core/order-flow';
import { UI } from '../shared/ui';
import { StatusComponent } from '../shared/status';
import { CancelDialog } from '../shared/confirm';
@Component({standalone:true,imports:[...UI,RouterLink,StatusComponent],template:`
<a class="back-link" [routerLink]="seller?'/vendedor/pedidos':'/comprador/pedidos'"><lucide-icon name="arrow-left" size="16"/> Volver a pedidos</a>
<div class="page-heading"><div><p class="eyebrow">DETALLE DEL PEDIDO</p><h1>Seguimiento</h1><p class="order-id muted">{{id}}</p></div><button mat-stroked-button (click)="reload()" [disabled]="loading()">Actualizar</button></div>
@if(loading()){<mat-progress-bar mode="indeterminate" aria-label="Cargando detalle"/>}
@if(error()){<div class="feedback error" role="alert"><p>{{error()}}</p><button mat-button (click)="reload()">Reintentar</button></div>}
@if(order();as o){<div class="order-summary"><div><span class="muted">Estado actual</span><p aria-live="polite"><app-status [state]="o.estado"/></p>@if(active(o.estado)){<small class="muted">Actualización automática cada 2,5 segundos</small>}</div><div><span class="muted">Almacén</span><p>{{o.almacenId}}</p></div>@if(o.zonaEntrega){<div><span class="muted">Zona de entrega</span><p>{{zoneLabel(o.zonaEntrega)}}</p></div>}</div>
@if(o.anulacionSolicitada){<p class="feedback warning" role="status">Se solicitó la anulación de este pedido.</p>}
<section class="detail-section"><h2>{{seller?'Tus productos':'Productos del pedido'}}</h2><div class="table-scroll"><table><thead><tr><th>SKU</th><th>Cantidad</th><th>Precio unitario</th><th>Peso unitario</th><th>Subtotal</th></tr></thead><tbody>@for(item of o.items;track item.sku){<tr><td>{{item.sku}}</td><td>{{item.cantidad}}</td><td>{{item.precioUnitario|number:'1.2-2'}}</td><td>{{item.pesoUnitario|number:'1.0-6'}} kg</td><td>{{item.subtotal|number:'1.2-2'}}</td></tr>}</tbody></table></div><dl class="totals"><div><dt>{{seller?'Subtotal de tus líneas':'Subtotal'}}</dt><dd>{{o.subtotal|number:'1.2-2'}}</dd></div>@if(!seller){<div><dt>Envío</dt><dd>{{o.envio===null?'Por calcular':(o.envio|number:'1.2-2')}}</dd></div><div class="total"><dt>Total</dt><dd>{{o.total===null?'Por calcular':(o.total|number:'1.2-2')}}</dd></div>}<div><dt>Peso</dt><dd>{{o.pesoTotal|number:'1.0-6'}} kg</dd></div></dl></section>
@if(!seller){<section class="detail-section"><h2>Proceso de despacho</h2><ol class="timeline">@for(step of timeline(o.pasos);track $index){<li><span class="timeline-dot"><lucide-icon [name]="step.estado==='COMPLETADO'?'check':'clock-3'" size="16"/></span><div><h3>{{stepLabel(step.paso)}}</h3><app-status [state]="step.estado"/><p class="muted">Intentos: {{step.intentos}} · {{step.ms===null?'Duración pendiente':step.ms+' ms'}}</p></div></li>}</ol></section><section class="detail-section"><h2>Guía de transporte</h2>@if(o.guia){<p>{{o.guia.id}} · {{o.guia.estado}}</p>}@else{<p class="muted">Todavía no hay una guía disponible.</p>}</section><section class="detail-section"><h2>Compensaciones</h2>@if(o.compensaciones.length){@for(step of o.compensaciones;track $index){<p>{{stepLabel(step.paso)}} · {{step.estado}} · {{step.intentos}} intentos · {{step.ms===null?'Duración pendiente':step.ms+' ms'}}</p>}}@else{<p class="muted">No se registran compensaciones.</p>}</section>@if(o.estado!=='DESPACHADO'&&o.estado!=='ANULADO'){<button mat-stroked-button color="warn" (click)="cancel()" [disabled]="cancelling()||o.anulacionSolicitada">{{cancelling()?'Solicitando…':'Solicitar anulación'}}</button>}}
}`,styles:[`.order-summary{display:flex;gap:40px;flex-wrap:wrap;padding:24px;background:var(--color-surface-soft);border-radius:var(--radius-md);margin:24px 0}.order-summary>.muted,.order-summary span.muted{font-size:12px}.detail-section{margin:28px 0}.totals{max-width:340px;margin:20px 0 20px auto}.totals>div{display:flex;justify-content:space-between;gap:20px;padding:8px}.totals dd{margin:0}.totals .total{border-top:1px solid var(--color-border);font-weight:650}.timeline{list-style:none;padding:8px 0}.timeline li{display:flex;gap:18px;position:relative;padding:0 0 24px}.timeline li:not(:last-child):before{content:'';position:absolute;left:17px;top:34px;bottom:0;border-left:1px solid var(--color-border)}.timeline-dot{flex-shrink:0;width:34px;height:34px;border-radius:50%;background:var(--color-primary-soft);color:var(--color-primary);display:grid;place-items:center}.timeline h3{margin:2px 0 10px;font-size:14px}.timeline p{font-size:12px}`]})
export class OrderDetailComponent implements OnInit {
 private api=inject(PedidosApiService);private route=inject(ActivatedRoute);private destroy=inject(DestroyRef);private dialog=inject(MatDialog);private notify=inject(Notifications);private refresh=new Subject<void>();
 seller=inject(SessionService).user()?.rol==='VENDEDOR';id=this.route.snapshot.paramMap.get('pedidoId')??'';order=signal<OrderDetail|null>(null);loading=signal(false);cancelling=signal(false);error=signal('');active=activeOrder;
 ngOnInit(){this.refresh.pipe(switchMap(()=>{this.loading.set(true);this.error.set('');return pollOrder(()=>this.api.detail(this.id)).pipe(tap(o=>{this.order.set(o);this.loading.set(false);}),catchError(e=>{this.error.set(errorMessage(e));this.loading.set(false);return EMPTY;}));}),takeUntilDestroyed(this.destroy)).subscribe();this.reload();}
 reload(){this.refresh.next();}
 cancel(){if(this.cancelling())return;this.dialog.open(CancelDialog,{width:'460px',maxWidth:'95vw'}).afterClosed().pipe(takeUntilDestroyed(this.destroy)).subscribe(yes=>{if(!yes)return;this.cancelling.set(true);this.api.cancel(this.id).pipe(takeUntilDestroyed(this.destroy),finalize(()=>this.cancelling.set(false))).subscribe({next:()=>{this.notify.show('Solicitud de anulación recibida.','info');this.reload();},error:e=>{this.notify.show(errorMessage(e),'error');this.reload();}});});}
 private normalized(p:string){return ({STOCK_RESERVAR:'RESERVAR_STOCK',STOCK_CONFIRMAR:'CONFIRMAR_DESPACHO',STOCK_LIBERAR:'LIBERAR_STOCK'} as Record<string,string>)[p]??p;}
 timeline(steps:ProcessStep[]){const normalized=steps.map(s=>({...s,paso:this.normalized(s.paso)}));const standard=['RESERVAR_STOCK','CALCULAR_ENVIO','GENERAR_GUIA','CONFIRMAR_DESPACHO'];return [...standard.flatMap(p=>{const matches=normalized.filter(s=>s.paso===p);return matches.length?matches:[{paso:p,estado:'PENDIENTE',intentos:0,ms:null}];}),...normalized.filter(s=>!standard.includes(s.paso))];}
 stepLabel(p:string){return ({RESERVAR_STOCK:'Reservar stock',CALCULAR_ENVIO:'Calcular envío',GENERAR_GUIA:'Generar guía',CONFIRMAR_DESPACHO:'Confirmar despacho',LIBERAR_STOCK:'Liberar stock',ANULAR_GUIA:'Anular guía'} as Record<string,string>)[this.normalized(p)]??p;}
 zoneLabel(zone:string){return ({LIMA_METROPOLITANA:'Lima Metropolitana',LIMA_PROVINCIA:'Lima Provincia',PROVINCIA:'Provincia'} as Record<string,string>)[zone]??zone;}
}
