import { Component, computed, DestroyRef, inject, OnInit, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { Router } from '@angular/router';
import { expand, EMPTY, finalize, reduce, from, mergeMap, catchError, of } from 'rxjs';
import { ProductosApiService } from '../core/api';
import { SessionService } from '../core/session';
import { Product, DeliveryZone, Stock } from '../core/models';
import { errorMessage, Notifications } from '../core/errors';
import { OrderDraft, WarehouseResolver } from '../core/order-flow';
import { UI } from '../shared/ui';
import { ProductDialog } from './product-dialog';
import { StockDialog } from './stock-dialog';
@Component({standalone:true,imports:[...UI,ReactiveFormsModule],providers:[OrderDraft],template:`
<div class="page-heading"><div><p class="eyebrow">{{seller?'TU INVENTARIO':'EXPLORA Y ELIGE'}}</p><h1>{{seller?'Productos':'Catálogo'}}</h1><p class="muted">{{seller?'Administra la información de tus productos.':'Encuentra los productos para tu próximo pedido.'}}</p></div>@if(seller){<button mat-flat-button color="primary" (click)="edit()"><lucide-icon name="plus" size="18"/> Nuevo producto</button>}</div>
@if(!seller){<div class="feedback info"><lucide-icon name="info" size="20"/><p>Cada pedido debe contener productos de un solo almacén. Puedes cambiar de almacén al vaciar tu selección.</p></div>}
@if(selectionError()){<p class="feedback warning" role="alert">{{selectionError()}}</p>}
<div class="list-toolbar"><span>{{visible().length}} productos{{seller?' propios':''}}</span><mat-form-field appearance="outline" class="search"><mat-label>Buscar en el catálogo</mat-label><input matInput [formControl]="search" placeholder="Nombre o SKU"/><lucide-icon matSuffix name="search" size="18"/></mat-form-field><button mat-icon-button (click)="load()" [disabled]="loading()" aria-label="Actualizar productos" matTooltip="Actualizar"><lucide-icon name="refresh-cw" size="19"/></button></div>
@if(loading()){<mat-progress-bar mode="indeterminate" aria-label="Cargando productos"/><div class="skeleton-grid" aria-hidden="true">@for(i of [1,2,3,4,5,6];track i){<div class="skeleton"></div>}</div>}
@else if(error()){<section class="empty" role="alert"><lucide-icon name="circle-alert"/><h2>No pudimos cargar los productos</h2><p>{{error()}}</p><button mat-stroked-button (click)="load()">Reintentar</button></section>}
@else if(!visible().length){<section class="empty"><lucide-icon name="package-search" size="36"/><h2>{{search.value?'Sin coincidencias':'Todavía no hay productos'}}</h2><p>{{search.value?'Prueba con otro nombre o SKU.':seller?'Registra tu primer producto para comenzar.':'Vuelve pronto para descubrir nuevos productos.'}}</p></section>}
@else {<div [class]="seller?'seller-products':'product-grid'">@if(seller){<div class="product-table-head"><span>Producto</span><span>Precio</span><span>Peso</span><span>Stock</span><span>Acciones</span></div>}@for(p of visible();track p.sku){<article class="product" [class.seller-row]="seller"><div class="product-identity">@if(!seller){<div class="product-art"><lucide-icon name="package" size="38"/></div>}<div><span class="sku">{{p.sku}}</span><h2>{{p.nombre}}</h2><small class="muted">Almacén: {{p.almacenId ?? 'Sin asignación'}}</small></div></div><div class="product-price"><span class="mobile-label">Precio</span>{{p.precio|number:'1.2-2'}}</div><div class="product-weight"><span class="mobile-label">Peso</span>{{p.peso|number:'1.0-6'}} kg</div><div class="stock-note">@if(stocks()[p.sku];as stock){<span>Disponible: {{stock.disponible}}<br>Reservado: {{stock.reservado}} · Total: {{stock.total}}</span>}@else if(!p.almacenId){<span>Almacén no disponible</span>}@else if(stockErrors()[p.sku]){<span>Stock no disponible</span><button mat-button (click)="loadStock(p)" [attr.aria-label]="'Reintentar stock '+p.sku">Reintentar</button>}@else{<span role="status">Consultando stock…</span>}</div><div class="product-action">@if(seller){<button mat-stroked-button (click)="edit(p)"><lucide-icon name="pencil" size="15"/> Editar</button><button mat-stroked-button (click)="editStock(p)" [disabled]="!p.almacenId" [attr.aria-label]="'Editar stock '+p.sku">Stock</button>}@else{<button mat-stroked-button color="primary" (click)="select(p)" [disabled]="draft.pending || selected().length>=20 || contains(p) || !p.almacenId"><lucide-icon name="plus" size="16"/>{{contains(p)?'Seleccionado':'Seleccionar'}}</button>}</div></article>}</div>}
@if(!seller && (selected().length || draft.pending)){<section class="selection"><h2>Tu selección</h2><p class="muted">Hasta 20 productos, con 1 a 50 unidades por producto.</p>@for(item of selected();track item.sku){<div class="selection-row"><span>{{item.nombre}} <small>{{item.sku}}</small></span><mat-form-field appearance="outline"><mat-label>Cantidad</mat-label><input matInput type="number" [value]="item.cantidad" min="1" max="50" step="1" [disabled]="draft.pending" (input)="quantity(item.sku,$event)"/></mat-form-field><button mat-icon-button [disabled]="draft.pending" (click)="remove(item.sku)" [attr.aria-label]="'Quitar '+item.nombre"><lucide-icon name="x" size="18"/></button></div>}
<form [formGroup]="checkout" (ngSubmit)="submit()"><mat-form-field appearance="outline"><mat-label>Zona de entrega</mat-label><mat-select formControlName="zonaEntrega"><mat-option value="LIMA_METROPOLITANA">Lima Metropolitana</mat-option><mat-option value="LIMA_PROVINCIA">Lima Provincia</mat-option><mat-option value="PROVINCIA">Provincia</mat-option></mat-select></mat-form-field><p class="muted" id="warehouse-note">{{warehouse()?'Almacén de origen: '+warehouse()+'. Revisa tu selección antes de confirmar.':'El producto debe tener un almacén asignado para enviar el pedido.'}}</p>@if(draft.pending){<p class="feedback warning" role="status">Hay una solicitud pendiente de confirmación. Al reintentar se conservarán sus datos e identificador.</p>}@if(orderError()){<p class="feedback error" role="alert">{{orderError()}}</p>}<button mat-flat-button color="primary" aria-describedby="warehouse-note" [disabled]="(!draft.pending && (!warehouse() || !validSelection() || checkout.invalid)) || sending()">{{sending()?'Enviando…':draft.pending?'Reintentar pedido':'Confirmar pedido'}}</button></form></section>}
`,styles:[`
.search{width:280px}.product-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.product{border:1px solid var(--color-border);border-radius:var(--radius-md);overflow:hidden;padding:20px;display:flex;flex-direction:column;align-items:flex-start;gap:12px}.product-identity{width:100%}.product-art{height:105px;display:grid;place-items:center;background:var(--color-surface-soft);color:var(--color-primary);border-radius:var(--radius-sm);margin-bottom:18px}.sku{font-size:11px;letter-spacing:.6px;color:var(--color-text-secondary)}.product h2{font-size:16px;line-height:1.4;margin:6px 0}.product-price{font-size:21px;font-weight:600}.product-weight,.stock-note{color:var(--color-text-secondary);font-size:12px}.stock-note{display:flex;align-items:center;gap:6px}.product-action{margin-top:auto;display:flex;gap:8px;flex-wrap:wrap}.mobile-label{display:none}.product-table-head,.seller-row{display:grid;grid-template-columns:minmax(180px,2fr) 1fr .8fr 1.5fr auto;align-items:center;gap:16px}.product-table-head{font-size:12px;color:var(--color-text-secondary);padding:14px 20px;background:var(--color-surface-soft)}.seller-row{border:0;border-bottom:1px solid var(--color-border);border-radius:0}.seller-row .product-price{font-size:14px}.seller-row .product-action{margin:0}.selection{border-top:1px solid var(--color-border);margin-top:32px;padding-top:24px;max-width:650px}.selection-row{display:flex;align-items:center;gap:16px}.selection-row>span{flex:1}.selection-row small{display:block;color:var(--color-text-secondary)}.selection-row mat-form-field{width:95px}.selection form>mat-form-field{width:100%}@media(max-width:1200px){.product-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.seller-products{display:grid;gap:16px}.product-table-head{display:none}.seller-row{display:flex;border:1px solid var(--color-border);border-radius:var(--radius-md)}.seller-row .mobile-label{display:inline;margin-right:8px;color:var(--color-text-secondary)}.search{flex:1;width:auto;min-width:160px}}@media(max-width:520px){.product-grid{grid-template-columns:1fr}.product-art{height:80px}.list-toolbar{flex-wrap:wrap}.search{order:3;flex-basis:100%}}
`]})
export class ProductsComponent implements OnInit {
 private api=inject(ProductosApiService);private auth=inject(SessionService);private dialog=inject(MatDialog);private destroy=inject(DestroyRef);private fb=inject(FormBuilder);private router=inject(Router);private notify=inject(Notifications);private resolver=inject(WarehouseResolver);
 readonly draft=inject(OrderDraft);readonly seller=this.auth.user()?.rol==='VENDEDOR';
 loading=signal(false);error=signal('');selectionError=signal('');stocks=signal<Record<string,Stock>>({});stockErrors=signal<Record<string,boolean>>({});all=signal<Product[]>([]);search=this.fb.nonNullable.control('');query=signal('');
 visible=computed(()=>this.all().filter(p=>(!this.seller||p.vendedorId===this.auth.user()?.id)&&`${p.sku} ${p.nombre}`.toLowerCase().includes(this.query().toLowerCase())));
 selected=signal<(Product&{cantidad:number})[]>([]);sending=signal(false);orderError=signal('');checkout=this.fb.nonNullable.group({zonaEntrega:['LIMA_METROPOLITANA' as DeliveryZone,Validators.required]});
 warehouse=computed(()=>{const rows=this.selected();if(!rows.length)return null;const ids=rows.map(p=>this.resolver.resolve(p));return ids[0]&&ids.every(id=>id===ids[0])?ids[0]:null;});
 validSelection=computed(()=>this.selected().length>0&&this.selected().every(p=>Number.isInteger(p.cantidad)&&p.cantidad>=1&&p.cantidad<=50));
 ngOnInit(){this.search.valueChanges.pipe(takeUntilDestroyed(this.destroy)).subscribe(q=>this.query.set(q));this.load();}
 load(){if(this.loading())return;this.loading.set(true);this.error.set('');let page=0;this.api.list().pipe(expand(rows=>rows.length===50?this.api.list(++page):EMPTY),reduce((all:Product[],rows)=>[...all,...rows],[]),takeUntilDestroyed(this.destroy),finalize(()=>this.loading.set(false))).subscribe({next:rows=>{this.all.set(rows);this.stocks.set({});this.stockErrors.set({});from(rows.filter(p=>!this.seller||p.vendedorId===this.auth.user()?.id)).pipe(mergeMap(p=>this.fetchStock(p),6),takeUntilDestroyed(this.destroy)).subscribe();},error:e=>this.error.set(errorMessage(e))});}
 edit(p:Product|null=null){this.dialog.open(ProductDialog,{data:p,width:'560px',maxWidth:'95vw'}).afterClosed().pipe(takeUntilDestroyed(this.destroy)).subscribe(saved=>{if(saved)this.load();});}
 contains(p:Product){return this.selected().some(i=>i.sku===p.sku);}
 select(p:Product){
  if(this.draft.pending||this.contains(p)||this.selected().length>=20)return;
  const warehouse=this.resolver.resolve(p);
  if(!warehouse){this.selectionError.set('Este producto no tiene un almacén disponible. Actualiza el catálogo.');return;}
  if(this.selected().length && this.warehouse()!==warehouse){this.selectionError.set('No puedes mezclar productos de almacenes diferentes en un pedido. Vacía tu selección para cambiar de almacén.');return;}
  this.selectionError.set('');this.selected.update(items=>[...items,{...p,cantidad:1}]);
 }
 private fetchStock(p:Product){const warehouse=this.resolver.resolve(p);if(!warehouse)return EMPTY;this.stockErrors.update(errors=>({...errors,[p.sku]:false}));return this.api.stock(p.sku,warehouse).pipe(mergeMap(stock=>{this.stocks.update(rows=>({...rows,[p.sku]:stock}));return of(stock);}),catchError(()=>{this.stockErrors.update(errors=>({...errors,[p.sku]:true}));return EMPTY;}));}
 loadStock(p:Product){this.fetchStock(p).pipe(takeUntilDestroyed(this.destroy)).subscribe();}
 editStock(p:Product){if(!this.resolver.resolve(p))return;this.dialog.open(StockDialog,{data:p,width:'480px',maxWidth:'95vw'}).afterClosed().pipe(takeUntilDestroyed(this.destroy)).subscribe((stock:Stock|undefined)=>{if(stock)this.stocks.update(rows=>({...rows,[p.sku]:stock}));});}
 quantity(sku:string,event:Event){const cantidad=Number((event.target as HTMLInputElement).value);this.selected.update(rows=>rows.map(p=>p.sku===sku?{...p,cantidad}:p));}
 remove(sku:string){this.selectionError.set('');this.selected.update(rows=>rows.filter(p=>p.sku!==sku));}
 submit(){const warehouse=this.warehouse();if(this.sending()||(!this.draft.pending&&(!warehouse||!this.validSelection()||this.checkout.invalid)))return;this.sending.set(true);this.checkout.disable();this.orderError.set('');this.draft.submit(warehouse??'',this.checkout.getRawValue().zonaEntrega,this.selected()).pipe(takeUntilDestroyed(this.destroy),finalize(()=>this.sending.set(false))).subscribe({next:order=>{this.draft.complete();this.selected.set([]);this.notify.show('Pedido registrado. Puedes seguir su avance aquí.','success');void this.router.navigate(['/comprador/pedidos',order.pedidoId]);},error:e=>this.orderError.set(errorMessage(e))});}
}
