import { BreakpointObserver } from '@angular/cdk/layout';
import { Component, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { MatSidenavModule } from '@angular/material/sidenav';
import { map } from 'rxjs';
import { SessionService } from '../core/session';
import { menus } from '../core/guards';
import { UI } from '../shared/ui';
@Component({standalone:true,imports:[...UI,RouterLink,RouterLinkActive,RouterOutlet,MatSidenavModule],template:`
<a class="skip-link" href="#main-content">Ir al contenido</a>
<mat-sidenav-container class="shell"><mat-sidenav #drawer [mode]="compact()?'over':'side'" [opened]="!compact()" class="sidebar"><div class="brand"><span class="brand-icon"><lucide-icon name="package-check"/></span><span>Gestión<br>de Pedidos</span></div><p class="nav-caption">ESPACIO DE TRABAJO</p><nav aria-label="Navegación principal">@for(item of menu;track item.path){<a [routerLink]="item.path" routerLinkActive="active" #active="routerLinkActive" [attr.aria-current]="active.isActive?'page':null" (click)="compact() && drawer.close()"><lucide-icon [name]="item.icon" size="20"/>{{item.label}}</a>}</nav><div class="sidebar-bottom"><lucide-icon name="circle-check" size="17"/><span>Todo comienza con un pedido</span></div></mat-sidenav>
<mat-sidenav-content><header class="topbar"><div class="topbar-left">@if(compact()){<button mat-icon-button (click)="drawer.toggle()" aria-label="Abrir menú"><lucide-icon name="menu"/></button>}<span class="workspace-label">Mi espacio</span></div><div class="user-area"><span class="avatar"><lucide-icon name="user-round" size="19"/></span><span class="user-info"><strong>{{auth.user()?.nombre}}</strong><span>{{auth.user()?.rol}}</span></span><button mat-icon-button (click)="auth.logout()" aria-label="Cerrar sesión" matTooltip="Cerrar sesión"><lucide-icon name="log-out" size="20"/></button></div></header><main id="main-content" class="main-content" tabindex="-1"><router-outlet/></main><footer class="shell-footer">Gestión de Pedidos · Tu operación, más clara.</footer></mat-sidenav-content></mat-sidenav-container>`,styles:[`
.shell{min-height:100dvh;background:var(--color-bg)}.sidebar{width:244px;border-right:1px solid var(--color-border);padding:32px 20px;background:var(--color-bg)}.sidebar .brand{font-size:17px;line-height:1.25;padding:0 8px}.nav-caption{font-size:10px;font-weight:650;letter-spacing:1.2px;color:var(--color-text-secondary);margin:44px 12px 16px}nav{display:grid;gap:6px}nav a{display:flex;align-items:center;gap:12px;padding:13px 14px;border-radius:var(--radius-md);color:var(--color-text-secondary);text-decoration:none;font-size:14px}nav a.active{background:var(--color-primary-soft);color:var(--color-primary);font-weight:600}.sidebar-bottom{display:flex;gap:8px;color:var(--color-text-secondary);font-size:11px;position:absolute;bottom:28px;left:24px;right:16px}.topbar{height:80px;border-bottom:1px solid var(--color-border);display:flex;align-items:center;justify-content:space-between;padding:0 40px;gap:12px}.topbar-left,.user-area{display:flex;align-items:center;gap:14px}.workspace-label{font-size:13px;color:var(--color-text-secondary)}.avatar{display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:var(--color-surface-soft)}.user-info{display:grid;gap:4px;font-size:12px}.user-info strong{font-weight:600;max-width:220px;overflow:hidden;text-overflow:ellipsis}.user-info>span{font-size:10px;letter-spacing:.7px;color:var(--color-text-secondary)}.main-content{padding:36px 40px;max-width:1440px;margin:auto;min-height:calc(100dvh - 138px)}.shell-footer{padding:18px 40px;color:var(--color-text-secondary);font-size:11px;border-top:1px solid var(--color-border)}@media(max-width:900px){.main-content{padding:28px 24px}.topbar{padding:0 20px;height:72px}}@media(max-width:520px){.main-content{padding:24px 16px}.topbar{padding:0 12px}.workspace-label{display:none}.user-info strong{max-width:160px}.shell-footer{padding:18px 16px}}
`]})
export class ShellComponent {
 readonly auth=inject(SessionService);compact=toSignal(inject(BreakpointObserver).observe('(max-width: 1000px)').pipe(map(v=>v.matches)),{initialValue:false});
 get menu(){return menus[this.auth.user()?.rol??'COMPRADOR'];}
}
